In [3]:
import numpy as np
import pandas as pd
from scipy.stats import bernoulli

## Missing Data Management - Probability Question
Construct a database with $100,000$ rows where each record has $100$ fields. Assume further that for each record, each of the $100$ fields has a $1$ per cent chance of being empty, i.e., its value is missing.

Remove all records with **two** or more empty fields and report the fraction of records that are removed.

In [26]:
df = pd.DataFrame(np.random.randint(0,100,size=(100000,100)), columns=np.arange(100))
df.replace(0, np.nan, inplace=True)
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,3.0,42.0,6.0,21.0,97.0,86.0,91.0,NaN,20.0,34.0,...,55.0,35.0,55.0,73.0,64.0,23.0,76.0,29.0,52.0,29.0
1,31.0,72.0,47.0,57.0,28.0,97.0,54.0,NaN,92.0,11.0,...,60.0,66.0,18.0,97.0,86.0,81.0,5.0,3.0,29.0,41.0
2,95.0,74.0,34.0,30.0,1.0,94.0,83.0,18.0,74.0,61.0,...,38.0,40.0,50.0,55.0,40.0,44.0,86.0,37.0,28.0,76.0
3,12.0,87.0,23.0,96.0,13.0,75.0,11.0,56.0,75.0,23.0,...,67.0,83.0,38.0,9.0,20.0,42.0,82.0,6.0,82.0,29.0
4,4.0,63.0,4.0,65.0,32.0,68.0,32.0,77.0,35.0,73.0,...,61.0,5.0,88.0,99.0,65.0,95.0,11.0,16.0,75.0,91.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,70.0,32.0,90.0,30.0,26.0,17.0,51.0,4.0,83.0,44.0,...,51.0,63.0,40.0,10.0,85.0,77.0,62.0,50.0,80.0,75.0
99996,94.0,86.0,61.0,45.0,73.0,20.0,92.0,97.0,73.0,61.0,...,96.0,91.0,82.0,52.0,63.0,57.0,5.0,50.0,77.0,85.0
99997,24.0,17.0,29.0,59.0,61.0,50.0,2.0,20.0,38.0,72.0,...,43.0,63.0,67.0,37.0,98.0,26.0,39.0,34.0,29.0,22.0
99998,15.0,74.0,12.0,58.0,94.0,27.0,81.0,5.0,47.0,95.0,...,44.0,81.0,NaN,1.0,86.0,56.0,68.0,79.0,45.0,86.0
99999,55.0,40.0,42.0,83.0,97.0,44.0,63.0,63.0,27.0,27.0,...,91.0,28.0,78.0,63.0,92.0,16.0,46.0,3.0,17.0,19.0

In [31]:
ndf=df.dropna(thresh=99, inplace=False)
ndf

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
4,4.0,63.0,4.0,65.0,32.0,68.0,32.0,77.0,35.0,73.0,...,61.0,5.0,88.0,99.0,65.0,95.0,11.0,16.0,75.0,91.0
5,39.0,60.0,18.0,44.0,84.0,60.0,47.0,84.0,9.0,47.0,...,7.0,89.0,67.0,19.0,40.0,55.0,39.0,13.0,46.0,84.0
7,1.0,80.0,89.0,97.0,36.0,82.0,19.0,67.0,5.0,41.0,...,12.0,76.0,41.0,71.0,31.0,84.0,16.0,84.0,55.0,44.0
8,2.0,79.0,60.0,49.0,38.0,93.0,54.0,66.0,68.0,98.0,...,21.0,38.0,70.0,38.0,26.0,27.0,65.0,87.0,80.0,NaN
9,21.0,96.0,64.0,88.0,81.0,58.0,37.0,93.0,8.0,60.0,...,5.0,25.0,26.0,19.0,2.0,17.0,58.0,59.0,28.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99993,86.0,6.0,35.0,79.0,48.0,49.0,75.0,19.0,81.0,72.0,...,16.0,71.0,89.0,43.0,73.0,95.0,39.0,7.0,92.0,45.0
99994,60.0,43.0,24.0,5.0,21.0,81.0,1.0,13.0,70.0,90.0,...,90.0,50.0,98.0,10.0,97.0,3.0,59.0,94.0,84.0,26.0
99996,94.0,86.0,61.0,45.0,73.0,20.0,92.0,97.0,73.0,61.0,...,96.0,91.0,82.0,52.0,63.0,57.0,5.0,50.0,77.0,85.0
99997,24.0,17.0,29.0,59.0,61.0,50.0,2.0,20.0,38.0,72.0,...,43.0,63.0,67.0,37.0,98.0,26.0,39.0,34.0,29.0,22.0
99999,55.0,40.0,42.0,83.0,97.0,44.0,63.0,63.0,27.0,27.0,...,91.0,28.0,78.0,63.0,92.0,16.0,46.0,3.0,17.0,19.0